import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
const temp = mkdtempSync(path.join(tmpdir(),'inkline-test-'));
let child, base, cookie, state, booking, logs = '';
async function start() {
  child = spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'0',DATABASE_PATH:path.join(temp,'studio.sqlite'),ADMIN_PASSWORD:'test-password-123'},windowsHide:true,stdio:['ignore','pipe','pipe']});
  child.stderr.on('data', chunk => logs += chunk);
  base = await new Promise((resolve,reject) => { const timer=setTimeout(()=>reject(new Error('Server timeout: '+logs)),10000); child.stdout.on('data', chunk => { const m=String(chunk).match(/http:\/\/127\.0\.0\.1:\d+/); if(m){clearTimeout(timer);resolve(m[0]);} }); child.once('exit',code=>{clearTimeout(timer);reject(new Error('Server exited '+code+logs));}); });
}
async function stop() { if (!child || child.exitCode !== null) return; const done=new Promise(resolve=>child.once('exit',resolve)); child.kill(); await done; }
async function call(route, method='GET', body, auth=false, extra={}) { const res=await fetch(base+'/api/'+route,{method,headers:{...(method==='GET'?{}:{'Content-Type':'application/json'}),...(auth?{Cookie:cookie}:{}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})}); return {status:res.status,body:await res.json(),res}; }
const date='2099-10-06';
const request = time => ({customerName:'Khách kiểm thử',phone:'0901234567',email:'a@example.com',artistId:'artist-minh',serviceId:'small',date,time,placement:'Vai',size:'5cm',notes:'Hoa nét mảnh',reference:''});
before(start);
after(async()=>{await stop();rmSync(temp,{recursive:true,force:true});});
test('public endpoint never exposes booking records or accounts',async()=>{const r=await call('public');assert.equal(r.status,200);assert.equal(r.body.bookings,undefined);assert.equal(r.body.users,undefined);state=r.body;});
test('requires server authentication for private data and mutations',async()=>{assert.equal((await call('admin')).status,401);assert.equal((await call('artists','POST',{name:'x'})).status,401);assert.equal((await call('login','POST',{username:'admin',password:'wrong'})).status,401);});
test('logs in using HttpOnly SameSite session cookie',async()=>{const r=await call('login','POST',{username:'admin',password:'test-password-123'});assert.equal(r.status,200);cookie=r.res.headers.get('set-cookie').split(';')[0];assert.match(r.res.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal((await call('session','GET',undefined,true)).body.authenticated,true);});
test('rejects cross-origin writes and blocks server/database files',async()=>{assert.equal((await call('services','POST',{},true,{Origin:'https://attacker.example'})).status,403);for(const file of ['/server.mjs','/seed.mjs','/data/studio.sqlite','/.env'])assert.equal((await fetch(base+file)).status,404);});
test('creates one booking when two clients race for overlapping time',async()=>{const results=await Promise.all([call('bookings','POST',request('10:00')),call('bookings','POST',request('10:30'))]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);booking=results.find(r=>r.status===201).body;assert.equal((await call('admin','GET',undefined,true)).body.bookings.length,1);});
test('enforces transition order and prevents premature completion',async()=>{assert.equal((await call('bookings/'+booking.id,'PATCH',{status:'Completed'},true)).status,400);assert.equal((await call('bookings/'+booking.id,'PATCH',{status:'Confirmed'},true)).status,200);assert.equal((await call('bookings/'+booking.id,'PATCH',{status:'Completed'},true)).status,400);});
test('reschedules across artist and time while retaining history',async()=>{const r=await call('bookings/'+booking.id,'PATCH',{artistId:'artist-linh',serviceId:'custom',date,time:'13:00'},true);assert.equal(r.status,200);assert.equal(r.body.duration,120);assert.equal(r.body.history.at(-1).action,'reschedule');});
test('cancelled bookings release slots and cannot reopen',async()=>{assert.equal((await call('bookings/'+booking.id,'PATCH',{status:'Cancelled'},true)).status,200);const a=await call('availability?'+new URLSearchParams({artistId:'artist-linh',serviceId:'custom',date}));assert.ok(a.body.times.includes('13:00'));assert.equal((await call('bookings/'+booking.id,'PATCH',{status:'Confirmed'},true)).status,400);});
test('validates booking data and unsafe reference URLs',async()=>{assert.equal((await call('bookings','POST',{...request('16:00'),phone:'bad'})).status,409);assert.equal((await call('bookings','POST',{...request('16:00'),reference:'javascript:alert(1)'})).status,400);});
test('CRUD content and referential integrity',async()=>{let r=await call('styles','POST',{name:'Test style',description:'Mô tả'},true);assert.equal(r.status,201);const id=r.body.id;r=await call('styles/'+id,'PUT',{name:'Tên mới',description:'Đã sửa'},true);assert.equal(r.body.name,'Tên mới');assert.equal((await call('styles/'+id,'DELETE',undefined,true)).status,200);assert.equal((await call('styles/fine-line','DELETE',undefined,true)).status,400);assert.equal((await call('artists/artist-minh','DELETE',undefined,true)).status,400);assert.equal((await call('services/custom','DELETE',undefined,true)).status,400);});
test('portfolio upload, blog content and hidden content filtering',async()=>{const image='data:image/png;base64,iVBORw0KGgo=';const p=await call('portfolio','POST',{title:'Tác phẩm mới',artistId:'artist-minh',styleId:'minimal',placement:'Vai',image,description:'Mô tả',visible:true},true);assert.equal(p.status,201);assert.equal(p.body.image,image);const b=await call('blog','POST',{title:'Bài mới',tag:'Studio',excerpt:'Tóm tắt',content:'Nội dung đầy đủ',visible:false},true);assert.equal(b.status,201);assert.ok(!(await call('public')).body.blog.some(x=>x.id===b.body.id));assert.equal((await call('blog/'+b.body.id,'DELETE',undefined,true)).status,200);});
test('settings update public content and validate business hours',async()=>{assert.equal((await call('settings','PUT',{...state.studio,openTime:'20:00',closeTime:'10:00'},true)).status,400);const r=await call('settings','PUT',{...state.studio,name:'Studio đã cập nhật'},true);assert.equal(r.status,200);assert.equal((await call('public')).body.studio.name,'Studio đã cập nhật');});
test('artist days off and visibility affect availability and portfolio',async()=>{const artist=state.artists[0];assert.equal((await call('artists/'+artist.id,'PUT',{...artist,daysOff:[date]},true)).status,200);assert.deepEqual((await call('availability?'+new URLSearchParams({artistId:artist.id,serviceId:'small',date}))).body.times,[]);await call('artists/'+artist.id,'PUT',{...artist,visible:false},true);const p=(await call('public')).body;assert.ok(!p.artists.some(a=>a.id===artist.id));assert.ok(!p.portfolio.some(a=>a.artistId===artist.id));});
test('persists settings and bookings across server restart',async()=>{await stop();await start();assert.equal((await call('public')).body.studio.name,'Studio đã cập nhật');assert.equal((await call('admin','GET',undefined,true)).body.bookings[0].id,booking.id);});
test('logout invalidates server session',async()=>{assert.equal((await call('logout','POST',{},true)).status,200);assert.equal((await call('admin','GET',undefined,true)).status,401);});
